#! /bin/sh

sxhkd &
# $HOME/.config/polybar/launch.sh
feh --bg-center $(find ~/wallpapers/ -type f | shuf -n 1)

if [[ $(hostname) == 'NL580']]; then
    bspc monitor DP1-1 -d 1 2 3
    bspc monitor DP1-2 -d 4 5 6
    bspc monitor eDP1 -d 7 8 9
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#46D9FF"
bspc config active_border_color "#5699AF"
bspc config normal_border_color "#282c34"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Anki state=floating
