#!/bin/bash
my_mac="88:C9:E8:18:94:2C"
mac="${my_mac//:/_}"

dbus-send --print-reply=literal --system --dest=org.bluez /org/bluez/hci0/dev_${mac} org.freedesktop.DBus.Properties.Get string:"org.bluez.Battery1" string:"Percentage" | awk '{print "#[fg=white]: 🎧 " $3 "%"}'
